[ENH] Use dbconfig to create db

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -17,10 +17,26 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+. /usr/share/debconf/confmodule
+
+if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
+        dbc_dbtypes="mysql"
+	echo "Creating database"
+        . /usr/share/dbconfig-common/dpkg/config
+	dbc_generate_include_owner="root:www-data"
+	dbc_generate_include_perms="0640"
+	dbc_generate_include=php:/etc/tiki9/db/local.php
+
+	if ! dbc_go tiki9 $@ ; then
+	        echo 'Automatic configuration using dbconfig-common failed!'
+	fi
+
+fi
 
 case "$1" in
     configure)
-    cd /usr/share/tiki9/htdocs; sh setup.sh -n
+	db_version 2.0
+	cd /usr/share/tiki9/htdocs; sh setup.sh -n
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
